# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CloudBurst
email: cloudburst@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 CloudBurst is a team of some young tech aspirants who are from different domains. 
 We are united to find a way that has no traces of conventionalism.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cloud_Burst
github_username:  CloudBurst

# Build settings
markdown: kramdown
